= Circuit Breaker - Fuse [Spring Boot] Booster

IMPORTANT: This runs best when deployed to OpenShift in order to use the circuit breaker functionality. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

IMPORTANT: This booster requires Java 8 JDK or greater and Maven 3.3.x or greater.

IMPORTANT: This booster can run in 3 modes: standalone on your machine, on your Single-node OpenShift Cluster and directly deployed by link:http://launch.openshift.io[]

IMPORTANT: As part of the process of creating this booster, launch.openshift.io set up a project with a CI/CD deployment of this booster. You can see the status of this deployment in your Single-node OpenShift Cluster or OpenShift Online Web Console.

== Running the Booster standalone on your machine
You can also run this booster as a standalone project directly:

. Obtain the project and enter the project's directory
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean package
----
. In *2 separate console* run the 2 services:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd name-service
$ mvn spring-boot:run -Dserver.port=8081
----
and
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd greetings-service
$ mvn spring-boot:run
----
. Follow the instructions visiting link:http://localhost:8080[]

== Running the Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:

. Log in and create your project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME
----
. Import base images in your newly created project (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fis-java-openshift:2.0 --from=registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0 --confirm
----
. Unzip, build and deploy your booster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift -Dfabric8.generator.fromMode=istag -Dfabric8.generator.from=MY_PROJECT_NAME/fis-java-openshift:2.0
----

== Running the Booster on launch.openshift.io
You can obtain this project directly from link:http://launch.openshift.io[]:
 . Visit link:http://launch.openshift.io[]
 . Follow the instructions to download a zip of the project or directly deploy it on Openshift Online.
