:launchURL: https://developers.redhat.com/launch
:image: registry.access.redhat.com/fuse7/fuse-java-openshift:1.0

= Circuit Breaker - Fuse Booster

== Overview
The Fuse circuit breaker booster consists of two related services:

* A _name service_ that returns a name to greet.
* A _greeting service_ that invokes the name service to get a name and then returns the `Hello, NAME` string.

This booster demonstrates inserting the Hystrix circuit breaker between the greeting service and the name service.
If the name service becomes unavailable, the circuit breaker instructs the greeting service to follow an alternative behavior and respond to the client immediately, thereby avoiding a blockage or time out condition while waiting for the name service to restart.

== Deployment options

You can run this booster in the following modes:

* Single-node OpenShift cluster
* OpenShift Online at link:{launchURL}[]
* Standalone on your machine

The most effective way to run this booster is to deploy and run the project on OpenShift.

For more details about running this booster on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

IMPORTANT: This booster requires Java 8 JDK or later and Maven 3.3.x or later.

== Running the booster on a single-node OpenShift cluster
A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your booster there.

To deploy this booster to a running single-node OpenShift cluster:

. Download the project and extract the archive on your local filesystem.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the booster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted booster application (for example, `my_openshift/fuse-springboot-circuit-breaker-booster`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/fuse-springboot-circuit-breaker-booster
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pods for the `name-service` application and for the `greetings-service` application have both started up.

. On the project's `Overview` page, locate the URL for the `fuse-springboot-circuit-breaker-booster` application: `http://greetings-service-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io`.

. Click the URL to access the Greeting Service application and then follow the instructions on that page.

[#single-node-without-preinstalled-images]
=== Running the booster on a single-node OpenShift cluster without preinstalled images
To deploy your booster to a running single-node OpenShift cluster without preinstalled images:

. Download the project and extract the archive on your local filesystem.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the booster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Import base images in your newly created project (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fis-java-openshift:2.0 --from={image} --confirm
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift -Dfabric8.generator.fromMode=istag -Dfabric8.generator.from=MY_PROJECT_NAME/fis-java-openshift:2.0
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pods for the `name-service` application and for the `greetings-service` application have both started up.

. On the project's `Overview` page, locate the URL for the `fuse-springboot-circuit-breaker-booster` application: `http://greetings-service-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io`.

. Click the URL to access the Greeting Service application and then follow the instructions on that page.

== Running the booster on OpenShift Online

To deploy the circuit breaker booster directly to OpenShift Online when you create the project at link:{launchURL}[]:

. Go to link:{launchURL}[].
. At the *Deployment step*, select *Use OpenShift Online*.
. Follow the on-screen instructions to create a new *Circuit Breaker* project using the *Fuse* runtime.

NOTE: As part of the process of creating this booster, link:{launchURL}[] sets up a project with a CI/CD deployment of this booster. You can see the status of this deployment in your single-node OpenShift cluster or OpenShift Online web console.

== Running the booster standalone on your machine
To run this booster as a standalone project on your local machine:

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. In two separate shell prompts, run the services:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd name-service
$ mvn spring-boot:run -Dserver.port=8081
----
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd greetings-service
$ mvn spring-boot:run
----
. Go to link:http://localhost:8080[] and then follow the instructions on that page.

