= Circuit Breaker - Fuse [Spring Boot] Booster

This booster can run in the following modes:

* Standalone on your machine
* Single-node OpenShift cluster
* OpenShift Online at link:http://launch.openshift.io[]

The most effective way to demonstrate the circuit breaker is to deploy and run the project on OpenShift.
For more details on running this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

IMPORTANT: This booster requires Java 8 JDK or greater and Maven 3.3.x or greater.


== Running the booster standalone on your machine
You can run this booster as a standalone project on your local machine:

. Download the project and extract the Zip file to your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. In two separate shell prompts, run the two services as follows:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd name-service
$ mvn spring-boot:run
----
and
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd greetings-service
$ mvn spring-boot:run
----
. Visit link:http://localhost:8080[] and follow the instructions on that page.

== Running the booster on a single-node OpenShift cluster
If you have a single-node OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your booster there.
A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:

. Download the project and extract the Zip file to your local filesystem.
. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----
. Create a new OpenShift project for the booster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----
. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----

== Running the booster on launch.openshift.io
You can deploy the circuit breaker booster directly to OpenShift Online when you create the project at link:http://launch.openshift.io[].

. Visit link:http://launch.openshift.io[].
. At the *Deployment step*, select *Use OpenShift Online*.
. Follow the on-screen instructions to create a new *Circuit Breaker* project using the *Fuse [Spring Boot]* runtime.

NOTE: As part of the process of creating this booster, launch.openshift.io sets up a project with a CI/CD deployment of this booster. You can see the status of this deployment in your Single-node OpenShift Cluster or OpenShift Online Web Consol
